🚧[Work In Progress] About Window
Stake-And-Rope/market-app pull request #33
Opened 2023-05-17 20:05 UTC by techfrapi

Related to #32

2023-05-17 20:40 UTC, karastoyanov commented on pyqt5-gui/about.py
> +        self.setGeometry(650, 300, 500, 200)
Change the window size to 500/300pxs

2023-05-17 20:49 UTC, karastoyanov approved these changes

2023-05-17 20:50 UTC, karastoyanov commented on pyqt5-gui/about.py
> +        self.setGeometry(650, 300, 500, 200)
Resolved with [10c00e7](https://github.com/Stake-And-Rope/market-app/pull/33/commits/10c00e7b104d37b4baf95ac5e1c0f8f312cb755f)

2023-05-21 17:23 UTC, techfrapi commented
Last commit https://github.com/Stake-And-Rope/market-app/commit/9f872eeb627d7feffe8952c59434c9011e6780aa
Added:
- Story About our company
- Contact us information
- Contributors - with names and link to Github

2023-05-21 19:05 UTC, karastoyanov commented on pyqt5-gui/about.py
> +
hgf

2023-05-21 21:50 UTC, karastoyanov commented on pyqt5-gui/about.py
> +        """Init the our story layout"""
Change the comments lines to upper letters only

2023-05-21 21:51 UTC, karastoyanov commented on pyqt5-gui/about.py
> +
you the `.setWindowIcon()` method to set the window icon. You can use the file `market.png` in img folder

2023-05-21 21:54 UTC, karastoyanov commented on pyqt5-gui/about.py
> +
Import customer font using the following block of code

```python
        font = QFontDatabase.addApplicationFont(r'../fonts/jetbrains-mono.regular.ttf')
        if font >= 0:
            fonts = QFontDatabase.applicationFontFamilies(font)
        else:
            print("Error loading fonts!")
```

Then, you can set the customer font to any object below, e.g.

```python
        contact_us = QLabel()
        contact_us.setText("<b><font size='4'>Contact Us</font></b><br>"
                           "123-456-7890<br>"
                           "stake_robe@example.com")
        contact_us.setFont(QFont(fonts[0], 12)) # where 12 is the font size
```

2023-05-21 21:56 UTC, karastoyanov requested changes
Check the following code reviews

2023-05-28 20:40 UTC, karastoyanov commented on pyqt5-gui/about.py
> +app.exec_()
test code review

2023-05-28 20:40 UTC, karastoyanov requested changes
take action

2023-05-28 20:45 UTC, karastoyanov approved these changes

2023-05-28 20:47 UTC, merged